;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        change-number-at-point
        indent-for-tab-command
        paredit-forward
        paredit-forward-delete
        paredit-kill
        paredit-wrap-round
        subtract-number-at-point
        ))

(setq mc/cmds-to-run-once
      '(
        mc--replace-region-strings-1
        ))
