;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-kill-sexp
        change-number-at-point
        cljr-slash
        clojure-forward-logical-sexp
        copy-region-or-current-line
        indent-for-tab-command
        kill-sexp
        markdown-outdent-or-delete
        paredit-forward
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-kill
        paredit-kill-region-or-backward-word
        paredit-raise-sexp
        paredit-semicolon
        paredit-wrap-round
        subtract-number-at-point
        wgrep-mark-deletion
        ))

(setq mc/cmds-to-run-once
      '(
        ))
