;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-kill-sexp
        change-number-at-point
        cider-load-buffer
        clj-hippie-expand-no-case-fold
        cljr-raise-sexp
        cljr-slash
        cljr-splice-sexp-killing-backward
        clojure-backward-logical-sexp
        clojure-forward-logical-sexp
        copy-region-or-current-line
        indent-for-tab-command
        kill-sexp
        markdown-outdent-or-delete
        paredit-C-j
        paredit-forward
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-kill
        paredit-kill-region-or-backward-word
        paredit-open-curly
        paredit-raise-sexp
        paredit-semicolon
        paredit-wrap-round
        paredit-wrap-square
        subtract-number-at-point
        wgrep-mark-deletion
        ))

(setq mc/cmds-to-run-once
      '(
        ))
